apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opa-tekton-sar-demo-cluster-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: opa-tekton-sar-demo
roleRef:
  kind: ClusterRole
  name: tekton-pipelines-controller-cluster-access
  apiGroup: rbac.authorization.k8s.io
