apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TektonClusterTaskAllowedServiceAccounts
metadata:
  name: taskrun-serviceaccount-allowed-clustertask
spec:
  match:
    kinds:
      - apiGroups: ["tekton.dev"]
        kinds: ["TaskRun"]
    namespaces:
      - "opa-tekton-sar-demo"
  parameters:
    apiServerURL: https://kubernetes.default.svc.cluster.local/apis/authorization.k8s.io/v1/subjectaccessreviews
    # UPDATE with a token from your cluster that can create SARS ...
    bearerTokenHeader: <Your_Bearer_Token>
    sarVerb: get
    sarGroup: tekton.dev
    sarResource: clustertasks
    sarResourceName: echo-hello-world
    taskRef:
      name: echo-hello-world
      kind: ClusterTask
