apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TektonClusterTaskAllowedServiceAccounts
metadata:
  name: taskrun-serviceaccount-allowed-clustertask
spec:
  match:
    kinds:
      - apiGroups: ["tekton.dev"]
        kinds: ["TaskRun"]
    namespaces:
      - "ggmtest"
  parameters:
    # UDPATE with your cluster's URL
    apiServerURL: https://<your api server external host and https port>/apis/authorization.k8s.io/v1/subjectaccessreviews
    # UPDATE with a token from your cluster that can create SARS ...
    bearerTokenHeader: Bearer you-actual-token
    sarVerb: get
    sarGroup: tekton.dev
    sarResource: clustertasks
    sarResourceName: echo-hello-world
    taskRef:
      name: echo-hello-world
      kind: ClusterTask
